// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package dao_account

import (
	"github.com/google/uuid"
	"github.com/stewie1520/blog/tools/types"
)

type Account struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	CreatedAt types.DateTime `json:"created_at"`
	UpdatedAt types.DateTime `json:"updated_at"`
	DeletedAt types.DateTime `json:"deleted_at"`
}

type Post struct {
	ID        uuid.UUID      `json:"id"`
	Content   string         `json:"content"`
	UserID    uuid.UUID      `json:"user_id"`
	CreatedAt types.DateTime `json:"created_at"`
	UpdatedAt types.DateTime `json:"updated_at"`
	DeletedAt types.DateTime `json:"deleted_at"`
}

type User struct {
	ID        uuid.UUID        `json:"id"`
	AccountID uuid.UUID        `json:"account_id"`
	FullName  string           `json:"full_name"`
	Bio       types.NullString `json:"bio"`
	CreatedAt types.DateTime   `json:"created_at"`
	UpdatedAt types.DateTime   `json:"updated_at"`
	DeletedAt types.DateTime   `json:"deleted_at"`
}
